<?php

namespace MoraleBundle\Repository;

/**
 * MoraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoraleRepository extends \Doctrine\ORM\EntityRepository
{
}
