piece:
    resource: "@PieceBundle/Controller/"
    type:     annotation
    prefix:   /
    
physique_physique:
    resource: "@PhysiqueBundle/Controller/PhysiqueController.php"
    type:     annotation

piece_piece:
    resource: "@PieceBundle/Controller/PieceController.php"
    type:     annotation

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

physique:
    resource: "@PhysiqueBundle/Controller/"
    type:     annotation
    prefix:   /

site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
