<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEb7vrgf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEb7vrgf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEb7vrgf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEb7vrgf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEb7vrgf\appProdProjectContainer(array(
    'container.build_hash' => 'Eb7vrgf',
    'container.build_id' => 'c8f79b27',
    'container.build_time' => 1632938714,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEb7vrgf');
