<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWcvnhgi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWcvnhgi/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWcvnhgi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWcvnhgi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWcvnhgi\appProdProjectContainer(array(
    'container.build_hash' => 'Wcvnhgi',
    'container.build_id' => '72118478',
    'container.build_time' => 1634235063,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWcvnhgi');
