<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1mptvxm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1mptvxm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1mptvxm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1mptvxm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1mptvxm\appDevDebugProjectContainer(array(
    'container.build_hash' => '1mptvxm',
    'container.build_id' => '9c7a259f',
    'container.build_time' => 1635266581,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1mptvxm');
