<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGjufg1l\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGjufg1l/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGjufg1l.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGjufg1l\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGjufg1l\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Gjufg1l',
    'container.build_id' => '8d9ee201',
    'container.build_time' => 1632496662,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGjufg1l');
