<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY9ogj1s\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY9ogj1s/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerY9ogj1s.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerY9ogj1s\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerY9ogj1s\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Y9ogj1s',
    'container.build_id' => '1fa68227',
    'container.build_time' => 1632938707,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY9ogj1s');
