<?php

namespace PhysiqueBundle\Repository;

/**
 * PhysiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysiqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByExampleField($value)
    {
        return $this->createQueryBuilder('a')
            ->Where('a.prenom LIKE :val')
            ->setParameter('val', $value.'%')
            ->orderBy('a.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }
}
