<?php

namespace Proxies\__CG__\PieceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Piece extends \PieceBundle\Entity\Piece implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'id', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'physique', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'typePiece', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'refPiece', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'datexpiration', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'datdeclaration', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'datedelivrance', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'emetteur', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'paysEmission', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'fichier'];
        }

        return ['__isInitialized__', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'id', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'physique', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'typePiece', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'refPiece', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'datexpiration', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'datdeclaration', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'datedelivrance', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'emetteur', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'paysEmission', '' . "\0" . 'PieceBundle\\Entity\\Piece' . "\0" . 'fichier'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Piece $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypePiece($typePiece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypePiece', [$typePiece]);

        return parent::setTypePiece($typePiece);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypePiece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypePiece', []);

        return parent::getTypePiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefPiece($refPiece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefPiece', [$refPiece]);

        return parent::setRefPiece($refPiece);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefPiece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefPiece', []);

        return parent::getRefPiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatexpiration($datexpiration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatexpiration', [$datexpiration]);

        return parent::setDatexpiration($datexpiration);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatexpiration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatexpiration', []);

        return parent::getDatexpiration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatdeclaration($datdeclaration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatdeclaration', [$datdeclaration]);

        return parent::setDatdeclaration($datdeclaration);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatdeclaration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatdeclaration', []);

        return parent::getDatdeclaration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedelivrance($datedelivrance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedelivrance', [$datedelivrance]);

        return parent::setDatedelivrance($datedelivrance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedelivrance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedelivrance', []);

        return parent::getDatedelivrance();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmetteur($emetteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmetteur', [$emetteur]);

        return parent::setEmetteur($emetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmetteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmetteur', []);

        return parent::getEmetteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaysEmission($paysEmission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaysEmission', [$paysEmission]);

        return parent::setPaysEmission($paysEmission);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaysEmission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaysEmission', []);

        return parent::getPaysEmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhysique(\PhysiqueBundle\Entity\Physique $physique = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhysique', [$physique]);

        return parent::setPhysique($physique);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhysique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhysique', []);

        return parent::getPhysique();
    }

    /**
     * {@inheritDoc}
     */
    public function setFichier($fichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFichier', [$fichier]);

        return parent::setFichier($fichier);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichier', []);

        return parent::getFichier();
    }

}
